# Generated by Django 3.2 on 2021-05-07 03:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='contact_no',
            field=models.BigIntegerField(default=1, max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'phone number must be 10 digits', 'Invalid phone number')]),
            preserve_default=False,
        ),
    ]
