# Generated by Django 3.1.7 on 2021-02-20 16:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ISBN',
            field=models.IntegerField(default=0, max_length=13, validators=[django.core.validators.RegexValidator('^\\d{13}$', 'Number must be 13 digits', 'Invalid number')]),
            preserve_default=False,
        ),
    ]
