# Generated by Django 3.2 on 2021-04-11 05:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0002_product_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ISBN',
            field=models.BigIntegerField(max_length=13, validators=[django.core.validators.RegexValidator('^\\d{13}$', 'Number must be 13 digits', 'Invalid number')]),
        ),
    ]
