# Generated by Django 3.2 on 2021-05-07 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0005_tax'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tax',
            old_name='tax_rate',
            new_name='tax_rate_in_percentage',
        ),
    ]
