# Generated by Django 3.2 on 2021-05-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0006_rename_tax_rate_tax_tax_rate_in_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping_Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_cost', models.FloatField()),
            ],
        ),
    ]
